apiVersion: v1
kind: ServiceAccount
metadata:
  name: beacon
  namespace: prysm

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: validator
  namespace: prysm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beacon
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beacon-rolebinding
roleRef:
  kind: ClusterRole
  name: beacon
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize specific service accounts:
- kind: ServiceAccount
  name: beacon
  namespace: prysm
- kind: ServiceAccount
  name: validator
  namespace: prysm
