{{- with .Values.beacon }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ $.Values.image.beaconImage }}:{{ $.Values.image.version }}"
        args:
        {{- if $.Values.ethereumTestnet }}
        - --{{ $.Values.ethereumTestnet }}
        {{- end }}
        - --rpc-host=0.0.0.0
        - --p2p-tcp-port={{ .p2pTcpPort }}
        - --p2p-udp-port={{ .p2pUdpPort }}
        - --http-web3provider={{ .web3Provider }}
        {{- range .fallbackWeb3Providers }}
        - --fallback-web3provider={{ . }}
        {{- end }}
        {{- if eq $.Values.persistentVolumeType "persistentVolumeClaim" }}
        - --datadir=/pv/data/prysm/beacon
        {{- if .genesisStateFile }}
        - --genesis-state=/pv{{ .genesisStateFile }}
        {{- end }}
        {{- else }}
        - --datadir=/data/prysm/beacon
        {{- if .genesisStateFile }}
        - --genesis-state={{ .genesisStateFile }}
        {{- end }}
        {{- end }}
        - --accept-terms-of-use
        ports:
        - containerPort: {{ .p2pTcpPort }}
          hostPort: {{ .p2pTcpPort }}
          protocol: TCP
        - containerPort: {{ .p2pUdpPort }}
          hostPort: {{ .p2pUdpPort }}
          protocol: UDP
        - containerPort: 4000
          protocol: TCP
        volumeMounts:
        {{- if eq $.Values.persistentVolumeType "persistentVolumeClaim" }}
        - name: beacon-storage
          mountPath: /pv
          readOnly: false
        {{- else }}
        - name: beacon-storage
          mountPath: /data/prysm/beacon
        {{- end }}
      volumes:
      - name: beacon-storage
        {{- if eq $.Values.persistentVolumeType "nfs" }}
        nfs:
          path: {{ .dataDirPath }}
          server: {{ $.Values.nfs.serverIp }}
          readOnly: false
        {{- else if eq $.Values.persistentVolumeType "hostPath" }}
        hostPath:
          path: {{ .dataDirPath }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ .name }}-pvc
        {{- end }}
      securityContext:
        {{- toYaml $.Values.securityContext | nindent 8 }}
      serviceAccountName: beacon
      restartPolicy: Always
{{- end }}
