{{- range $key, $validatorClient := .Values.validatorClients }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $validatorClient.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $validatorClient.name }}
spec:
  selector:
    matchLabels:
      app: {{ $validatorClient.name }}
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ $validatorClient.name }}
      annotations:
        checksum/config: {{ $validatorClient.walletPassword | sha256sum }}
    spec:
      initContainers:
      - name: init-wait
        image: alpine:3.13.2
        command: ['sh', '-c', 'echo "Wait for {{ $.Values.validatorStartWaitTime }} second(s) for extra slashing protection!" && sleep {{ $.Values.validatorStartWaitTime }}']
      containers:
      - name: {{ $validatorClient.name }}
        image: "{{ $.Values.image.validatorImage }}:{{ $.Values.image.version }}"
        args:
        {{- if $.Values.ethereumTestnet }}
        - --{{ $.Values.ethereumTestnet }}
        {{- end }}
        - --beacon-rpc-provider={{ $.Values.beacon.name }}-service.{{ $.Values.namespace }}.svc.cluster.local:4000
        {{- if eq $.Values.persistentVolumeType "persistentVolumeClaim" }}
        - --datadir=/pv{{ $validatorClient.dataDirPath }}
        - --wallet-dir=/pv{{ $validatorClient.walletDirPath }}
        {{- else }}
        - --datadir={{ $validatorClient.dataDirPath }}
        - --wallet-dir={{ $validatorClient.walletDirPath }}
        {{- end }}
        - --wallet-password-file=/data/prysm/password/wallet-pwd.txt
        - --graffiti={{ $validatorClient.graffiti | quote }}
        - --accept-terms-of-use
        volumeMounts:
        {{- if eq $.Values.persistentVolumeType "persistentVolumeClaim" }}
        - name: validator-storage
          mountPath: /pv
          readOnly: false
        {{- else }}
        {{- include "prysm.volumeMounts" $validatorClient | indent 8 }}
        {{- end }}
        - name: wallet-password
          mountPath: /data/prysm/password
          readOnly: true
      volumes:
      {{- if eq $.Values.persistentVolumeType "persistentVolumeClaim" }}
      - name: validator-storage
        persistentVolumeClaim:
          claimName: {{ .name }}-pvc
      {{- else }}
      {{- include "prysm.volumes" (merge $validatorClient (pick $.Values "persistentVolumeType" "nfs")) | indent 6 }}
      {{- end }}
      - name: wallet-password
        secret:
          secretName: {{ $validatorClient.walletPasswordSecretName }}
          items:
          - key: password
            path: wallet-pwd.txt
      securityContext:
        {{- toYaml $.Values.securityContext | nindent 8 }}
      serviceAccountName: validator-client
      restartPolicy: Always

---
{{- end }}
